language: php
php:
  # - "7.0"
  # - "7.1"
  - "7.2"
  - "7.3"


before_script:
  - composer install --dev --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build


script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml ./tests
  - vendor/bin/infection --min-msi=48 --threads=4

after_script:
  - php vendor/bin/coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
